apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    app.openshift.io/builder: maven
    app.openshift.io/runtime: openjdk
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"tekton.dev/v1beta1","kind":"Pipeline","metadata":{"annotations":{"app.openshift.io/builder":"maven","app.openshift.io/runtime":"openjdk"},"name":"ibm-java-maven","namespace":"tools"},"spec":{"params":[{"description":"The url for the git repository","name":"git-url"},{"default":"master","description":"The git revision (branch, tag, or sha) that should be built","name":"git-revision"},{"default":"true","description":"Enable the pipeline to scan the image for vulnerabilities","name":"scan-image"},{"default":"true","description":"Enable the pipeline to lint the Dockerfile for best practices","name":"lint-dockerfile"}],"tasks":[{"name":"setup","params":[{"name":"git-url","value":"$(params.git-url)"},{"name":"git-revision","value":"$(params.git-revision)"},{"name":"scan-image","value":"$(params.scan-image)"},{"name":"lint-dockerfile","value":"$(params.lint-dockerfile)"}],"taskRef":{"name":"ibm-setup-v2-6-10"}},{"name":"test","params":[{"name":"git-url","value":"$(tasks.setup.results.git-url)"},{"name":"git-revision","value":"$(tasks.setup.results.git-revision)"},{"name":"source-dir","value":"$(tasks.setup.results.source-dir)"},{"name":"app-name","value":"$(tasks.setup.results.app-name)"}],"runAfter":["setup"],"taskRef":{"name":"ibm-java-maven-test-v2-6-10"}},{"name":"dockerfile-lint","params":[{"name":"git-url","value":"$(tasks.setup.results.git-url)"},{"name":"git-revision","value":"$(tasks.setup.results.git-revision)"},{"name":"source-dir","value":"$(tasks.setup.results.source-dir)"},{"name":"lint-dockerfile","value":"$(tasks.setup.results.dockerfile-lint)"}],"runAfter":["test"],"taskRef":{"name":"ibm-dockerfile-lint-v2-6-10"}},{"name":"build","params":[{"name":"git-url","value":"$(tasks.setup.results.git-url)"},{"name":"git-revision","value":"$(tasks.setup.results.git-revision)"},{"name":"source-dir","value":"$(tasks.setup.results.source-dir)"},{"name":"image-server","value":"$(tasks.setup.results.image-server)"},{"name":"image-namespace","value":"$(tasks.setup.results.image-namespace)"},{"name":"image-repository","value":"$(tasks.setup.results.image-repository)"},{"name":"image-tag","value":"$(tasks.setup.results.image-tag)"}],"runAfter":["dockerfile-lint"],"taskRef":{"name":"ibm-build-tag-push-v2-6-10"}},{"name":"deploy","params":[{"name":"git-url","value":"$(tasks.setup.results.git-url)"},{"name":"git-revision","value":"$(tasks.setup.results.git-revision)"},{"name":"source-dir","value":"$(tasks.setup.results.source-dir)"},{"name":"image-server","value":"$(tasks.setup.results.image-server)"},{"name":"image-namespace","value":"$(tasks.setup.results.image-namespace)"},{"name":"image-repository","value":"$(tasks.setup.results.image-repository)"},{"name":"image-tag","value":"$(tasks.setup.results.image-tag)"},{"name":"app-namespace","value":"$(tasks.setup.results.app-namespace)"},{"name":"app-name","value":"$(tasks.setup.results.app-name)"},{"name":"deploy-ingress-type","value":"$(tasks.setup.results.deploy-ingress-type)"},{"name":"tools-image","value":"$(tasks.setup.results.tools-image)"}],"runAfter":["build"],"taskRef":{"name":"ibm-deploy-v2-6-10"}},{"name":"health","params":[{"name":"app-namespace","value":"$(tasks.setup.results.app-namespace)"},{"name":"app-name","value":"$(tasks.setup.results.app-name)"},{"name":"deploy-ingress-type","value":"$(tasks.setup.results.deploy-ingress-type)"},{"name":"health-protocol","value":"$(tasks.setup.results.health-protocol)"},{"name":"health-endpoint","value":"$(tasks.setup.results.health-endpoint)"},{"name":"health-url","value":"$(tasks.setup.results.health-url)"},{"name":"health-curl","value":"$(tasks.setup.results.health-curl)"},{"name":"tools-image","value":"$(tasks.setup.results.tools-image)"}],"runAfter":["deploy"],"taskRef":{"name":"ibm-health-check-v2-6-10"}},{"name":"tag-release","params":[{"name":"git-url","value":"$(tasks.setup.results.git-url)"},{"name":"git-revision","value":"$(tasks.setup.results.git-revision)"},{"name":"source-dir","value":"$(tasks.setup.results.source-dir)"},{"name":"js-image","value":"$(tasks.setup.results.js-image)"}],"runAfter":["health"],"taskRef":{"name":"ibm-tag-release-v2-6-10"}},{"name":"img-release","params":[{"name":"image-from","value":"$(tasks.setup.results.image-url)"},{"name":"image-to","value":"$(tasks.setup.results.image-release):$(tasks.tag-release.results.tag)"}],"runAfter":["tag-release"],"taskRef":{"name":"ibm-img-release-v2-6-10"}},{"name":"img-scan","params":[{"name":"image-url","value":"$(tasks.img-release.results.image-url)"},{"name":"scan-trivy","value":"$(tasks.setup.results.scan-trivy)"},{"name":"scan-ibm","value":"$(tasks.setup.results.scan-ibm)"}],"runAfter":["img-release"],"taskRef":{"name":"ibm-img-scan-v2-6-10"}},{"name":"helm-release","params":[{"name":"git-url","value":"$(tasks.setup.results.git-url)"},{"name":"git-revision","value":"$(tasks.setup.results.git-revision)"},{"name":"source-dir","value":"$(tasks.setup.results.source-dir)"},{"name":"image-url","value":"$(tasks.img-release.results.image-url)"},{"name":"app-name","value":"$(tasks.setup.results.app-name)"},{"name":"deploy-ingress-type","value":"$(tasks.setup.results.deploy-ingress-type)"},{"name":"tools-image","value":"$(tasks.setup.results.tools-image)"}],"runAfter":["img-scan"],"taskRef":{"name":"ibm-helm-release-v2-6-10"}},{"name":"gitops","params":[{"name":"app-name","value":"$(tasks.setup.results.app-name)"},{"name":"version","value":"$(tasks.tag-release.results.tag)"},{"name":"helm-url","value":"$(tasks.helm-release.results.helm-url)"},{"name":"tools-image","value":"$(tasks.setup.results.tools-image)"}],"runAfter":["helm-release"],"taskRef":{"name":"ibm-gitops-v2-6-10"}}]}}
  name: base-image-twas
  namespace: base-image-github
spec:
  params:
  - description: The url for the git repository
    name: git-url
    type: string
  - default: master
    description: The git revision (branch, tag, or sha) that should be built
    name: git-revision
    type: string
  - default: "true"
    description: Enable the pipeline to scan the image for vulnerabilities
    name: scan-image
    type: string
  - default: "true"
    description: Enable the pipeline to lint the Dockerfile for best practices
    name: lint-dockerfile
    type: string
  tasks:
  - name: setup
    params:
    - name: git-url
      value: $(params.git-url)
    - name: git-revision
      value: $(params.git-revision)
    - name: scan-image
      value: $(params.scan-image)
    - name: lint-dockerfile
      value: $(params.lint-dockerfile)
    taskRef:
      kind: Task
      name: ibm-setup-v2-6-10
  - name: dockerfile-lint
    params:
    - name: git-url
      value: $(tasks.setup.results.git-url)
    - name: git-revision
      value: $(tasks.setup.results.git-revision)
    - name: source-dir
      value: $(tasks.setup.results.source-dir)
    - name: lint-dockerfile
      value: $(tasks.setup.results.dockerfile-lint)
    runAfter:
    - setup
    taskRef:
      kind: Task
      name: ibm-dockerfile-lint-v2-6-10
  - name: build
    params:
    - name: git-url
      value: $(tasks.setup.results.git-url)
    - name: git-revision
      value: $(tasks.setup.results.git-revision)
    - name: source-dir
      value: $(tasks.setup.results.source-dir)
    - name: image-server
      value: $(tasks.setup.results.image-server)
    - name: image-namespace
      value: $(tasks.setup.results.image-namespace)
    - name: image-repository
      value: $(tasks.setup.results.image-repository)
    - name: image-tag
      value: $(tasks.setup.results.image-tag)
    runAfter:
    - dockerfile-lint
    taskRef:
      kind: Task
      name: ibm-build-tag-push-v2-6-10
  - name: deploy
    params:
    - name: git-url
      value: $(tasks.setup.results.git-url)
    - name: git-revision
      value: $(tasks.setup.results.git-revision)
    - name: source-dir
      value: $(tasks.setup.results.source-dir)
    - name: image-server
      value: $(tasks.setup.results.image-server)
    - name: image-namespace
      value: $(tasks.setup.results.image-namespace)
    - name: image-repository
      value: $(tasks.setup.results.image-repository)
    - name: image-tag
      value: $(tasks.setup.results.image-tag)
    - name: app-namespace
      value: $(tasks.setup.results.app-namespace)
    - name: app-name
      value: $(tasks.setup.results.app-name)
    - name: deploy-ingress-type
      value: $(tasks.setup.results.deploy-ingress-type)
    - name: tools-image
      value: $(tasks.setup.results.tools-image)
    runAfter:
    - build
    taskRef:
      kind: Task
      name: ibm-deploy-v2-6-10
  - name: health
    params:
    - name: app-namespace
      value: $(tasks.setup.results.app-namespace)
    - name: app-name
      value: $(tasks.setup.results.app-name)
    - name: deploy-ingress-type
      value: $(tasks.setup.results.deploy-ingress-type)
    - name: health-protocol
      value: $(tasks.setup.results.health-protocol)
    - name: health-endpoint
      value: $(tasks.setup.results.health-endpoint)
    - name: health-url
      value: $(tasks.setup.results.health-url)
    - name: health-curl
      value: $(tasks.setup.results.health-curl)
    - name: tools-image
      value: $(tasks.setup.results.tools-image)
    runAfter:
    - deploy
    taskRef:
      kind: Task
      name: ibm-health-check-v2-6-10
  - name: tag-release
    params:
    - name: git-url
      value: $(tasks.setup.results.git-url)
    - name: git-revision
      value: $(tasks.setup.results.git-revision)
    - name: source-dir
      value: $(tasks.setup.results.source-dir)
    - name: js-image
      value: $(tasks.setup.results.js-image)
    runAfter:
    - health
    taskRef:
      kind: Task
      name: ibm-tag-release-v2-6-10
  - name: img-release
    params:
    - name: image-from
      value: $(tasks.setup.results.image-url)
    - name: image-to
      value: $(tasks.setup.results.image-release):$(tasks.tag-release.results.tag)
    runAfter:
    - tag-release
    taskRef:
      kind: Task
      name: ibm-img-release-v2-6-10
  - name: img-scan
    params:
    - name: image-url
      value: $(tasks.img-release.results.image-url)
    - name: scan-trivy
      value: $(tasks.setup.results.scan-trivy)
    - name: scan-ibm
      value: $(tasks.setup.results.scan-ibm)
    runAfter:
    - img-release
    taskRef:
      kind: Task
      name: ibm-img-scan-v2-6-10
  - name: helm-release
    params:
    - name: git-url
      value: $(tasks.setup.results.git-url)
    - name: git-revision
      value: $(tasks.setup.results.git-revision)
    - name: source-dir
      value: $(tasks.setup.results.source-dir)
    - name: image-url
      value: $(tasks.img-release.results.image-url)
    - name: app-name
      value: $(tasks.setup.results.app-name)
    - name: deploy-ingress-type
      value: $(tasks.setup.results.deploy-ingress-type)
    - name: tools-image
      value: $(tasks.setup.results.tools-image)
    runAfter:
    - img-scan
    taskRef:
      kind: Task
      name: ibm-helm-release-v2-6-10
  - name: gitops
    params:
    - name: app-name
      value: $(tasks.setup.results.app-name)
    - name: version
      value: $(tasks.tag-release.results.tag)
    - name: helm-url
      value: $(tasks.helm-release.results.helm-url)
    - name: tools-image
      value: $(tasks.setup.results.tools-image)
    runAfter:
    - helm-release
    taskRef:
      kind: Task
      name: ibm-gitops-v2-6-10
